let
    Source = {Number.From(#date(2025,1,1))..Number.From(#date(2030,12,31))},
    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Column1", type date}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "Date"}}),
    #"Inserted Year" = Table.AddColumn(#"Renamed Columns", "Year", each Date.Year([Date]), Int64.Type),
    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([Date]), Int64.Type),
    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([Date]), type text),
    #"Inserted Quarter" = Table.AddColumn(#"Inserted Month Name", "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
    #"Inserted Week of Year" = Table.AddColumn(#"Inserted Quarter", "Week of Year", each Date.WeekOfYear([Date]), Int64.Type),
    #"Inserted Day Name" = Table.AddColumn(#"Inserted Week of Year", "Day Name", each Date.DayOfWeekName([Date]), type text),
    #"Inserted Day" = Table.AddColumn(#"Inserted Day Name", "Day", each Date.Day([Date]), Int64.Type),
    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Day", "Day of Week", each Date.DayOfWeek([Date]), Int64.Type),
    #"Inserted Start of Month" = Table.AddColumn(#"Inserted Day of Week", "Start of Month", each Date.StartOfMonth([Date]), type date),
    #"Inserted End of Month" = Table.AddColumn(#"Inserted Start of Month", "End of Month", each Date.EndOfMonth([Date]), type date),
    #"Inserted Start of Week" = Table.AddColumn(#"Inserted End of Month", "Start of Week", each Date.StartOfWeek([Date]), type date),
    #"Inserted End of Week" = Table.AddColumn(#"Inserted Start of Week", "End of Week", each Date.EndOfWeek([Date]), type date),
    #"Added Custom" = Table.AddColumn(#"Inserted End of Week", "Today", each DateTime.Date(DateTime.LocalNow())),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Today", type date}, {"End of Week", type date}, {"Start of Week", type date}, {"End of Month", type date}, {"Start of Month", type date}}),
    #"Added Custom2" = Table.AddColumn(#"Changed Type1", "Week Offset", each (Number.From(Date.StartOfWeek([Date]))
-
Number.From(Date.StartOfWeek(DateTime.LocalNow()))) / 7),
    #"Added Conditional Column" = Table.AddColumn(#"Added Custom2", "This/Last week", each if [Week Offset] = 0 then "This Week" else if [Week Offset] = -1 then "Last Week" else null),
    #"Added Custom3" = Table.AddColumn(#"Added Conditional Column", "Month Offset", each ((Date.Year([Date]) -
Date.Year(DateTime.LocalNow())) * 12)
+ Date.Month([Date]) - 
Date.Month(DateTime.LocalNow())),
    #"Added Conditional Column1" = Table.AddColumn(#"Added Custom3", "This/Last Month", each if [Month Offset] = 0 then "This Month" else if [Month Offset] = -1 then "Last Month" else null),
    #"Added Conditional Column2" = Table.AddColumn(#"Added Conditional Column1", "Is Weekend", each if [Day of Week] = 5 then 1 else if [Day of Week] = 6 then 1 else 0),
    #"Merged Queries" = Table.NestedJoin(#"Added Conditional Column2", {"Date"}, DimBankHolidays, {"Bank Holidays"}, "DimBankHolidays", JoinKind.LeftOuter),
    #"Expanded DimBankHolidays" = Table.ExpandTableColumn(#"Merged Queries", "DimBankHolidays", {"Bank Holidays"}, {"Bank Holidays"}),
    #"Added Conditional Column3" = Table.AddColumn(#"Expanded DimBankHolidays", "Is Holiday", each if [Bank Holidays] <> null then 1 else 0),
    #"Added Custom1" = Table.AddColumn(#"Added Conditional Column3", "Is Working Day?", each if [Is Weekend] = 0 and [Is Holiday] = 0 then 1 else 0)
in
    #"Added Custom1"